<?php defined('SYSPATH') OR die('No direct access allowed.');
// DO NOT EDIT
// This file is automatically generated from the matching PO file
// Updates should be made through Transifex
// I18n generated at: 2012-09-07 12:07+0000
// PO revision date:  2012-08-19 22:46+0000
$lang = array(
	'table_not_found' => 'Tabla "%s" no puede ser encontrada en la base de datos. Por favor asegúrese que está usando la versión más reciente de la base de datos para esta versión de Ushahidi.',
);
